multiSigAddr = "0x6f574c6325B3cB3F86E8bfA5f306310D63dD217d"
dexAddr = "0x8835f3bcEB451Ea73f0Ef3891f47bc66c7D24306"
tigAddr = "0xAD027A891f961F40cFc48a5f5E17F84Aeab63152"
dracoAddr = "0x61463DdC7dB3538008C3764e5A447baaD15FC4a8"
creditAddr = "0xa693A9254dD481Ba917eEE1466CC8d10EFD8eb91"
serverAddr = "0x406A1Ee747CEEA7a8819Bb999c3B24cc88000461"

serverPrivateKey = "69ALjXEQwVVm9iY1GT2r1Sus3mUkivIQJ5Ke3jWuak2Z4kmn96T1mKlgyl82u/PrPi+yZmY4M1WW83lvD0dL9hTXLEOSQNe7JQudost9ehk="
secondPrivateKey = "w9XK5uj8obtf+V4+paxDKor3KcnQtUT/skbkEwBFoCxrA8ObMwc3o2lSd7QC6FEDcG5TwmqIgQLDTBxTAaVeAgF76lEsRo/HEny+sb/aB84="

rawURL = "https://api.test.wemix.com"

channelToken = "sQBklzGzM5A2VsU/mELtgbkEfu2ISdI3cBZ0IXQJut8vLHsusv7Iwghm+Ob104Ss"
botToken = "y9nI+d6QUNWKIUDtTYMy7crLWREYPpP45/IN2fzEFdu2dAF4ehmCd+ZzdBBzy3YAKjGKiN/tDkVLwcksMcnH4xaFCDoqFPHsWrIA+TEkvII6HJi1jH9B21u/SfxNdZR6"