multiSigAddr = "qLm++1/25hRVXYL8aFWxWWjSkBV2YB/iFzpYmHz222pArd7+XgzqT7MTmDw9G9EiL5a2ELOvnOK4n80v3wR85Q=="
dexAddr = "Q64LglGBj9ANOvPjma4wYhfuRRXjyRiSKfjZs62NLNrh/gns1qyyHd4zewSGvMdie6RC4De8IhIBdB6Kv26TFg=="
creditAddr = "xiNc/lV2GyX5954BZPvEC6aj11ZNMK7Z6zIFNNE1R4Zxikm1Kduq5nc9/l1ryvi5MB7CrNiiISGv9yHnwW/FgQ=="
dracoAddr = "WLlxaXo9XbAqZgi6qWIYY9YNvGBjtvietSN1H7Ys9THibSDj3tOOxvH096X77T34Oq2rKb77MRSoDCKV0MqSgA=="
tigAddr = "7xH5+LYkSWZKV0gnwPT88+FqiQOcU+htNkiondDMEzpesPLmwZwAjnm0Bylez1n/7hObc4C3kNA9Hxz0OzLw5g=="
serverPrivateKey = "69ALjXEQwVVm9iY1GT2r1Sus3mUkivIQJ5Ke3jWuak2Z4kmn96T1mKlgyl82u/PrPi+yZmY4M1WW83lvD0dL9hTXLEOSQNe7JQudost9ehk="
serverAddr = "0x406A1Ee747CEEA7a8819Bb999c3B24cc88000461"
rawURL = "https://api.test.wemix.com"
secondPrivateKey = "w9XK5uj8obtf+V4+paxDKor3KcnQtUT/skbkEwBFoCxrA8ObMwc3o2lSd7QC6FEDcG5TwmqIgQLDTBxTAaVeAgF76lEsRo/HEny+sb/aB84="
botToken = "y9nI+d6QUNWKIUDtTYMy7crLWREYPpP45/IN2fzEFdu2dAF4ehmCd+ZzdBBzy3YAKjGKiN/tDkVLwcksMcnH4xaFCDoqFPHsWrIA+TEkvII6HJi1jH9B21u/SfxNdZR6"
channelToken = "sQBklzGzM5A2VsU/mELtgbkEfu2ISdI3cBZ0IXQJut8vLHsusv7Iwghm+Ob104Ss"