multiSigAddr = "0x778A13935292235614c6d518612c176B587e1341"
dexAddr = "0x678293568Ec517FF9AfC1CBf870054b42FC3F67E"
tigAddr = "0xb8A5A46197Dc7cFc3EC19d881b82Aa6A99165658"
dracoAddr = "0x03EdAE75B178Cb09DfE85b50136d5133d89417A1"
creditAddr = "0x98353411852ca63675832ED1f2Ed40efFdb140d9"

serverAddr = "0x406A1Ee747CEEA7a8819Bb999c3B24cc88000461"

serverPrivateKey = "69ALjXEQwVVm9iY1GT2r1Sus3mUkivIQJ5Ke3jWuak2Z4kmn96T1mKlgyl82u/PrPi+yZmY4M1WW83lvD0dL9hTXLEOSQNe7JQudost9ehk="
secondPrivateKey = "w9XK5uj8obtf+V4+paxDKor3KcnQtUT/skbkEwBFoCxrA8ObMwc3o2lSd7QC6FEDcG5TwmqIgQLDTBxTAaVeAgF76lEsRo/HEny+sb/aB84="

rawURL = "https://api.test.wemix.com/"

botToken = "y9nI+d6QUNWKIUDtTYMy7crLWREYPpP45/IN2fzEFdu2dAF4ehmCd+ZzdBBzy3YAKjGKiN/tDkVLwcksMcnH4xaFCDoqFPHsWrIA+TEkvII6HJi1jH9B21u/SfxNdZR6"
channelToken = "sQBklzGzM5A2VsU/mELtgbkEfu2ISdI3cBZ0IXQJut8vLHsusv7Iwghm+Ob104Ss"