multiSigAddr = "0x529B1b28fDead3f17D5A902314aA66b0Fc6ce6eB"
dexAddr = "0x3B351317408572e206f35492095635c1Ef1388C1"
tigAddr = "0x004bAa21722fbB7E4895e37d7191DE2C7faF082b"
dracoAddr = "0x21D7758Ccc12C17f29a6eAB8243D96921C2E0C61"
creditAddr = "0x0238f0Db32108dAE5A06C13e731D418B9d84cb7D"

serverAddr = "0x406A1Ee747CEEA7a8819Bb999c3B24cc88000461"

serverPrivateKey = "69ALjXEQwVVm9iY1GT2r1Sus3mUkivIQJ5Ke3jWuak2Z4kmn96T1mKlgyl82u/PrPi+yZmY4M1WW83lvD0dL9hTXLEOSQNe7JQudost9ehk="
secondPrivateKey = "w9XK5uj8obtf+V4+paxDKor3KcnQtUT/skbkEwBFoCxrA8ObMwc3o2lSd7QC6FEDcG5TwmqIgQLDTBxTAaVeAgF76lEsRo/HEny+sb/aB84="

rawURL = "https://api.test.wemix.com/"

botToken = "y9nI+d6QUNWKIUDtTYMy7crLWREYPpP45/IN2fzEFdu2dAF4ehmCd+ZzdBBzy3YAKjGKiN/tDkVLwcksMcnH4xaFCDoqFPHsWrIA+TEkvII6HJi1jH9B21u/SfxNdZR6"
channelToken = "sQBklzGzM5A2VsU/mELtgbkEfu2ISdI3cBZ0IXQJut8vLHsusv7Iwghm+Ob104Ss"