serverPrivateKey = "69ALjXEQwVVm9iY1GT2r1Sus3mUkivIQJ5Ke3jWuak2Z4kmn96T1mKlgyl82u/PrPi+yZmY4M1WW83lvD0dL9hTXLEOSQNe7JQudost9ehk="
multiSigAddr = "5peHy4ff3k45wNMxsNWhEy6y1XWxuJ25Cb3WeCsZ7HxV8gAPjV00Faoies2XYlNKyKQG4VbW1pvkC8+n7DPsSA=="
dexAddr = "gAir/aRUj6Z7ii5C0OgM6qRyGg5d2ZNiLknIYIvbb2FieNUhC9li6/6vWiNhrHXomv8UvOLZaF64aBzBcSUeUA=="
creditAddr = "nt7NQpCcwXllmDdnq4bygud1JLPnSolrpHOnCNaXgAU/RObaD2rDmBo/o9WbVHWElSZmhiSkXknixzDzCG1qng=="
dracoAddr = "U5ZVz5UMJW0gZlLw24y4xkl/MNtoH7XKeVq1dITO1bQPSW2zblD8pKAWWty1juI17614JuKxw8ci5zLx6yYdCg=="
tigAddr = "8UgZ+50Uw2vOAp8yXwAjAfRWiIu7VQjNpmy61qH/SsQ2OTCShMLGpMojLTl67E5n/8TdDvqLFSjL3hM9WwcT/g=="
serverAddr = "0x406A1Ee747CEEA7a8819Bb999c3B24cc88000461"
rawURL = "https://api.test.wemix.com"