firsdtPk = "tczzOhlnAtweLPNP4rCkifhWQBXbWBEJjwZbyUJpi9M7jF+2nx+j/6Hsy9HERZlebr7Bm6cANlGC4mgQOjZPwl/scVRzbn9CDjMcnSec0Yw="
multiSigAddr = "xuRO0ChwSP6J36lIOP2N/ys8jGYicS8onPw92xPzvYz1kKERMtPPA62URky7RYBhWhAIUpLvr7F/w+IJIrbryA=="
dexAddr = "CahtQYFdS1KkZMxG0bb+3amZx00JMBuo24DVHjzgHoFlPurLXk06Gq/uuauSkCQj9wvwBfjcSWeMAECnDwQEPw=="
creditAddr = "Fq2KPgaOjs1RFb5QGvIBnpI4aWwAKv4vYmF/Q2HAZ/lMVDQQAtGdzMmOfh78LQuRLEdCxqu3NT8doh7dRwR9zg=="
dracoAddr = "kBbDQ55DNHEswqUbU5SuC7kecdF8n9XN0LcOllwqDVis8rmyh8GcOumpoIrEn71fhpy5lOQpuNxVwuGM9v2fCQ=="
tigAddr = "Y34ZymfE7rGrioPDEDKgj52sOYSLO7TSsWP3QC5+gSa6pvVpRY7jlUADvTaqnWgJUhfTkwa5xKsPrt6p3lhimw=="
