serverPrivateKey = "69ALjXEQwVVm9iY1GT2r1Sus3mUkivIQJ5Ke3jWuak2Z4kmn96T1mKlgyl82u/PrPi+yZmY4M1WW83lvD0dL9hTXLEOSQNe7JQudost9ehk="
multiSigAddr = "jTgfccZ8uZRtVbtQX28clN+olVbKUVkJLDeYlyZVJQ+J08+iy01T221T0qq8kpo1NvSgNOm4XcL5TASgua/d5Q=="
dexAddr = "gvLgJ0iljJjsHMDn0Y/wXHb3+qSvPsqYOjyU/X76HBR2RLQfKG1PMvQ84/zFzx3K5Ga2YUrW2rOFhQ9OKKjmlw=="
creditAddr = "Fq2KPgaOjs1RFb5QGvIBnpI4aWwAKv4vYmF/Q2HAZ/lMVDQQAtGdzMmOfh78LQuRLEdCxqu3NT8doh7dRwR9zg=="
dracoAddr = "kBbDQ55DNHEswqUbU5SuC7kecdF8n9XN0LcOllwqDVis8rmyh8GcOumpoIrEn71fhpy5lOQpuNxVwuGM9v2fCQ=="
tigAddr = "Y34ZymfE7rGrioPDEDKgj52sOYSLO7TSsWP3QC5+gSa6pvVpRY7jlUADvTaqnWgJUhfTkwa5xKsPrt6p3lhimw=="
serverAddr = "0x406A1Ee747CEEA7a8819Bb999c3B24cc88000461"
rawURL = "https://api.test.wemix.com"
channelToken = "+KDt5uPgnputxuNkZUIcSaoKw+3DfTUi8mcuOCfiJMtFqXxZXRsiXQx5nY2RFhA7Gm6eL9s7fZNXLbwF7oFW3H9XIi71zxTv+RmP6VbItYLa8j60ABbVBFHh0/hTYDNk"
secondPrivateKey = "w9XK5uj8obtf+V4+paxDKor3KcnQtUT/skbkEwBFoCxrA8ObMwc3o2lSd7QC6FEDcG5TwmqIgQLDTBxTAaVeAgF76lEsRo/HEny+sb/aB84="
botToken = "YIufP/JzwuV9+DnpebLCKFMiHdcjW7Pfe7a3rNfbBqd9kEHZD49mXp2ZBdMdKWZVUTr61Lq8aPyfs8li/nuqULR7zoQA4Bb4U4GIf0hUsF3Q4xEYpSn2vSNgxUs4OMoo"