[network]
url = "wss://ws.test.wemix.com"

[db]
host = "mongodb://localhost:27017"

[addr]
dexAddr = "0x8835f3bcEB451Ea73f0Ef3891f47bc66c7D24306"
tigAddr = "0xAD027A891f961F40cFc48a5f5E17F84Aeab63152"
dracoAddr = "0x61463DdC7dB3538008C3764e5A447baaD15FC4a8"
creditAddr = "0xa693A9254dD481Ba917eEE1466CC8d10EFD8eb91"