[info]
firstpk = "ed60003d1d768f0c2690b9ae3c418a0a1515abd0569de3701ac273bee0257003"
secondpk = "2e33f33e005a4ed8986cbf4770ee022b4d28b59d7d078bc5a82e7be2c97e8f44"
bottoken = "MTA2NTE2OTY5NTM0MDI0NTA0NA.GILwNt.2hpQ2b7_w0J_VQldtTZGUnV5IENLIfYk3-80Rg"
multisigaddr = "0x6f574c6325B3cB3F86E8bfA5f306310D63dD217d"
channelid = "1065174473822711828"